---
title: "Data Manipulation for the DT App"
author: "Samuel Jones"
date: "2022-11-02"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
Weekly2 <- readRDS("~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/Weekly2.rds")
# A crypto market visualization that was abandoned as it was not exclusively Australian Data
meth_plot <- ggplot(Weekly2[(Weekly2$Week> "2020-10-08" & Weekly2$Week < "2022-05-31"),] %>% filter(DrugAZ == "Meth/amphetamine (illicit)" & listing > 250), aes(x= Week, y = listing, color = MarketAZ)) + geom_line()
```

```{r}
ggplotly(meth_plot)
```
```{r}
library(foreign)
library(haven)
#Treatment data modification
TreatmentGrandViz <- read_dta("TreatmentGrandViz.dta")

TreatmentGrandViz$Location <- ifelse(TreatmentGrandViz$Location == "AUS", "Australia",
                              ifelse(TreatmentGrandViz$Location == "ACT", "Australian Capital Territory",
                                     ifelse(TreatmentGrandViz$Location == "NSW", "New South Wales",
                                            ifelse(TreatmentGrandViz$Location == "NT", "Northern Territory",
                                                   ifelse(TreatmentGrandViz$Location == "WA", "Western Australia",
                                                          ifelse(TreatmentGrandViz$Location == "VIC", "Victoria",
                                                                 ifelse(TreatmentGrandViz$Location == "QLD", "Queensland", 
                                                                        ifelse(TreatmentGrandViz$Location == "SA", "South Australia", 
                                                                               ifelse(TreatmentGrandViz$Location == "TAS", "Tasmania*", TreatmentGrandViz$Location)))))))))
    
TreatmentGrandViz$Drug <- ifelse(TreatmentGrandViz$Drug == "All", "All drugs",
                                     ifelse(TreatmentGrandViz$Drug == "Amphetamine-type stimulant", "Amphetamine-type stimulants", TreatmentGrandViz$Drug))
write.dta(TreatmentGrandViz, "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/TreatmentGrandViz.dta")
  
```
```{r}
# Deaths data modification
load("~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/death_2020.Rdata")
COD2020_DT$jurisdiction[COD2020_DT$jurisdiction == "Tasmania"] <- "Tasmania*"

COD2020_DT$cr[COD2020_DT$cr == 0] <- NA
    
COD2020_DT$Drug <- ifelse(COD2020_DT$Drug == "AMPHETAMINES", "Amphetamine-type stimulants",
                              ifelse(COD2020_DT$Drug == "COCAINE", "Cocaine",
                                     ifelse(COD2020_DT$Drug == "CANNABINOIDS", "Cannabinoids",
                                            ifelse(COD2020_DT$Drug == "heroin", "Heroin", COD2020_DT$Drug))))
COD2020_All$Drug <- "All drugs"
COD2020_All$jurisdiction[COD2020_All$jurisdiction == "Tasmania"] <- "Tasmania*"
save(COD2020_DT, file = "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/death_2020.Rdata")
save(COD2020_All, file = "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/death_2020.Rdata")
```
```{r}
drugtypes.data <- readRDS("~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/drugtypes.data.rds")

drugtypes.data <- drugtypes.data[c(1,2,11,13,14,18,19),]
saveRDS(drugtypes.data, "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/drugtypes.data.rds")
drugtypes.data <- readRDS("~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/drugtypes.data.rds")

```

```{r}
IDRS_use <- readRDS("~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/IDRS_use.rds")
IDRS_use <- subset(IDRS_use, var_year != 2000 & var_year != 2001)
IDRS_use <- IDRS_use[c(1:18)]
IDRS_use[c('methweekly_N', 'cocaineweekly_N', 'cannabisweekly_N', 'heroinweekly_N')] <- IDRS_use[c('anymethu_N', 'anycocaine_N', 'anycannabis_N', 'anyheroin_N')]
IDRS_use$istate[IDRS_use$istate == "Aus"] <- "Australia"
IDRS <- IDRS_use %>% pivot_longer(-c(var_year, istate),
               names_to = c("Drug", ".value"), 
               names_sep="_" )
confi <- epi.conf(cbind(IDRS$n, IDRS$N), ctype = "prevalence", method = "exact", conf.level = 0.95)
```
```{r}
IDRS <- cbind(IDRS, confi)
IDRS$DrugType <- ifelse(grepl("^any", IDRS$Drug), "any", 
                      ifelse(grepl("weekly$", IDRS$Drug), "weekly", NA))

# Create separate columns for each drug type
IDRS_any <- subset(IDRS, DrugType == "any")[,c("var_year", "istate", "Drug", "est", "lower", "upper")]
colnames(IDRS_any)[4:6] <- paste(colnames(IDRS_any)[4:6], "any", sep="_")

IDRS_weekly <- subset(IDRS, DrugType == "weekly")[,c("var_year", "istate", "Drug", "est", "lower", "upper")]
colnames(IDRS_weekly)[4:6] <- paste(colnames(IDRS_weekly)[4:6], "weekly", sep="_")
```
```{r}
IDRS$Drug <- ifelse(IDRS$Drug == "methweekly", "Methamphetamine",
                                         ifelse(IDRS$Drug == "cocaineweekly", "Cocaine",
                                                ifelse(IDRS$Drug == "cannabisweekly", "Cannabis", 
                                                       ifelse(IDRS$Drug == "heroinweekly", "Heroin", IDRS$Drug))))
IDRS$Drug <- ifelse(IDRS$Drug == "anymethu", "Methamphetamine",
                                         ifelse(IDRS$Drug == "anycocaine", "Cocaine",
                                                ifelse(IDRS$Drug == "anycannabis", "Cannabis", 
                                                       ifelse(IDRS$Drug == "anyheroin", "Heroin", IDRS$Drug))))
```
```
IDRS_use$Methamphetamine_any <- round(IDRS_use$anymethu_n/IDRS_use$anymethu_N, digits = 2)*100
IDRS_use$Methamphetamine_weekly <- round(IDRS_use$methweekly_n/IDRS_use$anymethu_N, digits = 2)*100
IDRS_use$Cocaine_any <- round(IDRS_use$anycocaine_n/IDRS_use$anycocaine_N, digits = 2)*100
IDRS_use$Cocaine_weekly <- round(IDRS_use$cocaineweekly_n/IDRS_use$anycocaine_N, digits = 2)*100
IDRS_use$Cannabis_any <- round(IDRS_use$anycannabis_n/IDRS_use$anycannabis_N, digits = 2)*100
IDRS_use$Cannabis_weekly <- round(IDRS_use$cannabisweekly_n/IDRS_use$anycannabis_N, digits = 2)*100
IDRS_use$Heroin_any <- round(IDRS_use$anyheroin_n/IDRS_use$anyheroin_N, digits = 2)*100
IDRS_use$Heroin_weekly <- round(IDRS_use$heroinweekly_n/IDRS_use$anyheroin_N, digits = 2)*100

keeps <- c("var_year","istate","Methamphetamine_any","Methamphetamine_weekly", "Cocaine_any", "Cocaine_weekly", "Cannabis_any", "Cannabis_weekly", "Heroin_any", "Heroin_weekly")
IDRS <- IDRS_use[,keeps, drop=FALSE]
#IDRS_long <- gather(IDRS, freq, rate, anymeth:heroinweekly, factor_key = TRUE)
saveRDS(IDRS_use, "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/IDRS_use.rds")

```

```{r}
EDRS_use <- readRDS("~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/EDRS_use.rds")


```

```{r}
#EDRS_use$Methamphetamine_any <- round(EDRS_use$anymethu_n/EDRS_use$anymethu_N, digits = 2)*100
#EDRS_use$Methamphetamine_weekly <- round(EDRS_use$methweekly_n/EDRS_use$anymethu_N, digits = 2)*100
#EDRS_use$Cocaine_any <- round(EDRS_use$anycocaine_n/EDRS_use$anycocaine_N, digits = 2)*100
#EDRS_use$Cocaine_weekly <- round(EDRS_use$cocaineweekly_n/EDRS_use$anycocaine_N, digits = 2)*100
#EDRS_use$Cannabis_any <- round(EDRS_use$anycannabis_n/EDRS_use$anycannabis_N, digits = 2)*100
#EDRS_use$Cannabis_weekly <- round(EDRS_use$cannabisweekly_n/EDRS_use$anycannabis_N, digits = 2)*100
#EDRS_use$Heroin_any <- round(EDRS_use$anyheroin_n/EDRS_use$anyheroin_N, digits = 2)*100

keeps2[c('methweekly_N', 'cocaineweekly_N', 'cannabisweekly_N')] <- keeps2[c('anymethu_N', 'anycocaine_N', 'anycannabis_N')]
keeps2[is.na(keeps2)] <- 0
EDRS <- keeps2 %>% pivot_longer(-c(var_year, istate),
               names_to = c("Drug", ".value"), 
               names_sep="_" )
confi <- epi.conf(cbind(EDRS$n, EDRS$N), ctype = "prevalence", method = "exact", conf.level = 0.95)
#EDRS_use[,keeps2, drop=FALSE]
#saveRDS(EDRS_use, "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/EDRS_use.rds")
```
```{r}
#EDRS <- cbind(EDRS, confi)
EDRS <- EDRS[-c(4:8)]
EDRS <- EDRS %>% pivot_longer(-c(var_year, istate),
               names_to = c("Drug", ".value"), 
               names_sep="_" )
```
```{r}
EDRS$DrugType <- ifelse(grepl("^any", EDRS$Drug), "any", 
                      ifelse(grepl("weekly$", EDRS$Drug), "weekly", NA))

# Create separate columns for each drug type
EDRS_any <- subset(EDRS, DrugType == "any")[,c("var_year", "istate", "Drug", "est", "lower", "upper")]
colnames(EDRS_any)[4:6] <- paste(colnames(EDRS_any)[4:6], "any", sep="_")

EDRS_weekly <- subset(EDRS, DrugType == "weekly")[,c("var_year", "istate", "Drug", "est", "lower", "upper")]
colnames(EDRS_weekly)[4:6] <- paste(colnames(EDRS_weekly)[4:6], "weekly", sep="_")
```
```{r}
EDRS_any$Drug <- ifelse(EDRS_any$Drug == "anymethu", "Methamphetamine",
                                         ifelse(EDRS_any$Drug == "anycocaine", "Cocaine",
                                                ifelse(EDRS_any$Drug == "anycannabis", "Cannabis",
                                                       ifelse(EDRS_any$Drug == "anyheroin", "Heroin", EDRS_any$Drug))))
EDRS_any$istate[EDRS_any$istate == "Aus"] <- "Australia"
EDRS_any$est_any <- round(EDRS_any$est_any, digits = 2)*100
EDRS_any$lower_any <- round(EDRS_any$lower_any, digits = 2)*100
EDRS_any$upper_any <- round(EDRS_any$upper_any, digits = 2)*100
```
```{r}
EDRS_weekly$Drug <- ifelse(EDRS_weekly$Drug == "methweekly", "Methamphetamine",
                                         ifelse(EDRS_weekly$Drug == "cocaineweekly", "Cocaine",
                                                ifelse(EDRS_weekly$Drug == "cannabisweekly", "Cannabis", EDRS_weekly$Drug)))
EDRS_weekly$istate[EDRS_weekly$istate == "Aus"] <- "Australia"
EDRS_weekly$est_weekly <- round(EDRS_weekly$est_weekly, digits = 2)*100
EDRS_weekly$lower_weekly <- round(EDRS_weekly$lower_weekly, digits = 2)*100
EDRS_weekly$upper_weekly <- round(EDRS_weekly$upper_weekly, digits = 2)*100
```

```{r}
new_rows <- data.frame(var_year = rep(2003, 9),
                        istate = c("Australia", "NSW", "VIC", "TAS", "QLD", "WA", "NT", "ACT", "SA"),
                        Drug = rep("Heroin", 9),
                        est = rep(NA_real_, 9),
                        lower = rep(NA_real_, 9),
                        upper = rep(NA_real_, 9),
                        DrugType = rep("weekly", 9))

# add the new rows to your original data frame using rbind()
EDRS <- rbind(EDRS, new_rows)

```






```{r}
IDRS <- IDRS %>% pivot_longer(-c(var_year, istate),
               names_to = c("Drug", ".value"), 
               names_sep="_" )
IDRS$istate[IDRS$istate == "Aus"] <- "Australia"
saveRDS(IDRS, "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/IDRS.rds")

```
```{r}
EDRS <- EDRS %>% pivot_longer(-c(var_year, istate),
               names_to = c("Drug", ".value"), 
               names_sep="_" )
EDRS$istate[EDRS$istate == "Aus"] <- "Australia"
saveRDS(EDRS, "~/Documents/MSc HDS/Dissertation/Experimental_shiny_design/EDRS.rds")

```
```{r}
library(epiR)
confi <- epi.conf(cbind(IDRS_use$anymethu_n, IDRS_use$anymethu_N), ctype = "prevalence", method = "exact", conf.level = 0.95)
confi2 <- epi.conf(cbind(IDRS$any, IDRS$denominator), ctype = "prevalence", method = "exact", conf.level = 0.85)
```